CREATE TABLE insumos_agro (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100),
    fornecedor VARCHAR2(100),
    unidade VARCHAR2(10),
    quantidade NUMBER(10,2),
    consumo NUMBER(10,2),
    lead_time NUMBER,
    estoque_minimo NUMBER(10,2),
    data_cadastro DATE,
    data_aviso_compra DATE
);
