CREATE TABLE sistema_irrigacao (
  id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  umidade   NUMBER(5,2),
  ph        NUMBER(4,2),
  fosforo   VARCHAR2(10),
  potassio  VARCHAR2(10),
  bomba     VARCHAR2(10)
);
